version: "3.5"
name: "simple-house-services"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: simple-house-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "simple-house"
      POSTGRES_PASSWORD: "password"
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - "8010:5432"

volumes:
  database-data:
