version: "3.8"
name: "simple-house-services"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: simple-house-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "8010:5432"

volumes:
  db:
